Module HandleReport
    Sub CetakHistoriPembayaran(ByVal Tampung As DataTable, ByVal TglAwal As Date, ByVal TglAkhir As Date)
        Dim SourceHTML As String = ""
        SourceHTML &= vbCrLf & "<html>"
        SourceHTML &= vbCrLf & "<head>"
        SourceHTML &= vbCrLf & "'<meta http-equiv=Content-Type content=""text/html; charset=windows-1252"">"
        SourceHTML &= vbCrLf & "<meta name = Generator content=""Microsoft Word 15 (filtered)"">"
        SourceHTML &= vbCrLf & "<style>"
        SourceHTML &= vbCrLf & "<!--"
        SourceHTML &= vbCrLf & " /* Font Definitions */"
        SourceHTML &= vbCrLf & " @font-face"
        SourceHTML &= vbCrLf & "	{font-family:""Cambria Math"";"
        SourceHTML &= vbCrLf & "	panose-1: 2 4 5 3 5 4 6 3 2 4;}"
        SourceHTML &= vbCrLf & "@font-face"
        SourceHTML &= vbCrLf & "	{font-family:Calibri;"
        SourceHTML &= vbCrLf & "	panose-1: 2 15 5 2 2 2 4 3 2 4;}"
        SourceHTML &= vbCrLf & " /* Style Definitions */"
        SourceHTML &= vbCrLf & " p.MsoNormal, li.MsoNormal, div.MsoNormal"
        SourceHTML &= vbCrLf & "	{margin-top:0in;"
        SourceHTML &= vbCrLf & "	margin-Right(): 0in;"
        SourceHTML &= vbCrLf & "	margin-bottom: 8.0pt;"
        SourceHTML &= vbCrLf & "	margin-Left(): 0in;"
        SourceHTML &= vbCrLf & "	line-height: 107%;"
        SourceHTML &= vbCrLf & "	Font-Size: 11.0pt;"
        SourceHTML &= vbCrLf & "	Font-family: ""Calibri"",sans-serif;}"
        SourceHTML &= vbCrLf & ".MsoChpDefault"
        SourceHTML &= vbCrLf & "	{font-family:""Calibri"",sans-serif;}"
        SourceHTML &= vbCrLf & ".MsoPapDefault"
        SourceHTML &= vbCrLf & "	{margin-bottom:8.0pt;"
        SourceHTML &= vbCrLf & "	line-height: 107%;}"
        SourceHTML &= vbCrLf & "@page WordSection1"
        SourceHTML &= vbCrLf & "	{size:841.9pt 595.3pt;"
        SourceHTML &= vbCrLf & "	margin:.5in .5in .5in .5in;}"
        SourceHTML &= vbCrLf & "div.WordSection1"
        SourceHTML &= vbCrLf & "	{page:WordSection1;}"
        SourceHTML &= vbCrLf & "-->"
        SourceHTML &= vbCrLf & "</style>"

        SourceHTML &= vbCrLf & "</head>"

        SourceHTML &= vbCrLf & "<body lang = EN - US >"

        SourceHTML &= vbCrLf & "<div Class=WordSection1>"

        SourceHTML &= vbCrLf & "<p Class=MsoNormal align=center style='margin-bottom:0in;margin-bottom:.0001pt;"
        SourceHTML &= vbCrLf & "text-align:center'><b><span style='font-size:14.0pt;line-height:107%;"
        SourceHTML &= vbCrLf & "font-family:""Arial"",sans-serif'>LAPORAN HISTORI PEMBAYARAN</span></b></p>"

        SourceHTML &= vbCrLf & "<p Class=MsoNormal align=center style='margin-bottom:0in;margin-bottom:.0001pt;"
        SourceHTML &= vbCrLf & "text-align:center'><b><span style='font-size:14.0pt;line-height:107%;"
        SourceHTML &= vbCrLf & "font-family:""Arial"",sans-serif'>PERIODE " & TglAwal.ToString("dd-MM-yyyy") & " S/D " & TglAkhir.ToString("dd-MM-yyyy") & " </span></b></p>"

        SourceHTML &= vbCrLf & "<p Class=MsoNormal align=center style='margin-bottom:0in;margin-bottom:.0001pt;"
        SourceHTML &= vbCrLf & "text-align:center'><b><span style='font-family:""Arial"",sans-serif'>&nbsp;</span></b></p>"

        SourceHTML &= vbCrLf & "<table>"
        SourceHTML &= vbCrLf & "<tr>"

        Select Case My.Settings.Role
            Case "admin"
                SourceHTML &= vbCrLf & "<td>Id Admin </td>"
            Case "petugas"
                SourceHTML &= vbCrLf & "<td>Id Petugas </td>"
            Case "siswa"
                SourceHTML &= vbCrLf & "<td>NISN </td>"
        End Select

        SourceHTML &= vbCrLf & "<td>: " & My.Settings.CurrentId & " </td>"
        SourceHTML &= vbCrLf & "</tr>"
        SourceHTML &= vbCrLf & "<tr>"

        Select Case My.Settings.Role
            Case "admin"
                SourceHTML &= vbCrLf & "<td>Nama Admin </td>"
            Case "petugas"
                SourceHTML &= vbCrLf & "<td>Nama Petugas </td>"
            Case "siswa"
                SourceHTML &= vbCrLf & "<td>Nama Siswa </td>"
        End Select

        SourceHTML &= vbCrLf & "<td>: " & My.Settings.Username & " </td>"
        SourceHTML &= vbCrLf & "</tr>"
        SourceHTML &= vbCrLf & "</table>"

        SourceHTML &= vbCrLf & "<table Class=MsoTable15Grid4 border=1 cellspacing=0 cellpadding=0 width=1080"
        SourceHTML &= vbCrLf & " style='width:11.25in;margin-left:-18.25pt;border-collapse:collapse;border:"
        SourceHTML &= vbCrLf & " none;margin:0 auto'>"
        SourceHTML &= vbCrLf & " <tr style ='height:31.9pt'>"
        SourceHTML &= vbCrLf & "  <td width=36 style='width:27.0pt;border:solid black 1.0pt;border-right:none;"
        SourceHTML &= vbCrLf & "  background:black;padding:0in 5.4pt 0in 5.4pt;height:31.9pt'>"
        SourceHTML &= vbCrLf & "	  <p class=MsoNormal align=center style='margin-bottom:0in;margin-bottom:.0001pt;"
        SourceHTML &= vbCrLf & "  text-align:center;line-height:normal'><b><span style='font-family:""Arial"",sans-serif;"
        SourceHTML &= vbCrLf & "  color:white'>No</span></b></p>"
        SourceHTML &= vbCrLf & "  </td>"
        SourceHTML &= vbCrLf & "  <td width = 99 style='width:74.1pt;border-top:solid black 1.0pt;border-left:"
        SourceHTML &= vbCrLf & "  none;border-bottom:solid black 1.0pt;border-right:none;background:black;"
        SourceHTML &= vbCrLf & "  padding:0in 5.4pt 0in 5.4pt;height:31.9pt'>"
        SourceHTML &= vbCrLf & "  <p Class=MsoNormal align=center style='margin-bottom:0in;margin-bottom:.0001pt;"
        SourceHTML &= vbCrLf & "  text-align:center;line-height:normal'><b><span style='font-family:""Arial"",sans-serif;"
        SourceHTML &= vbCrLf & "  color:white'>Tgl.Bayar</span></b></p>"
        SourceHTML &= vbCrLf & "  </td>"
        SourceHTML &= vbCrLf & "  <td width = 104 style='width:78.15pt;border-top:solid black 1.0pt;border-left:"
        SourceHTML &= vbCrLf & "  none;border-bottom:solid black 1.0pt;border-right:none;background:black;"
        SourceHTML &= vbCrLf & "  padding:0in 5.4pt 0in 5.4pt;height:31.9pt'>"
        SourceHTML &= vbCrLf & "  <p Class=MsoNormal align=center style='margin-bottom:0in;margin-bottom:.0001pt;"
        SourceHTML &= vbCrLf & "  text-align:center;line-height:normal'><b><span style='font-family:""Arial"",sans-serif;"
        SourceHTML &= vbCrLf & "  color:white'>ID.</span></b></p>"
        SourceHTML &= vbCrLf & "  <p Class=MsoNormal align=center style='margin-bottom:0in;margin-bottom:.0001pt;"
        SourceHTML &= vbCrLf & "  text-align:center;line-height:normal'><b><span style='font-family:""Arial"",sans-serif;"
        SourceHTML &= vbCrLf & "  color:white'>Pembayaran</span></b></p>"
        SourceHTML &= vbCrLf & "  </td>"
        SourceHTML &= vbCrLf & "  <td width = 87 style='width:65.25pt;border-top:solid black 1.0pt;border-left:"
        SourceHTML &= vbCrLf & "  none;border-bottom:solid black 1.0pt;border-right:none;background:black;"
        SourceHTML &= vbCrLf & "  padding:0in 5.4pt 0in 5.4pt;height:31.9pt'>"
        SourceHTML &= vbCrLf & "  <p Class=MsoNormal align=center style='margin-bottom:0in;margin-bottom:.0001pt;"
        SourceHTML &= vbCrLf & "  text-align:center;line-height:normal'><b><span style='font-family:""Arial"",sans-serif;"
        SourceHTML &= vbCrLf & "  color:white'>ID.</span></b></p>"
        SourceHTML &= vbCrLf & "  <p Class=MsoNormal align=center style='margin-bottom:0in;margin-bottom:.0001pt;"
        SourceHTML &= vbCrLf & "  text-align:center;line-height:normal'><b><span style='font-family:""Arial"",sans-serif;"
        SourceHTML &= vbCrLf & "  color:white'>Petugas</span></b></p>"
        SourceHTML &= vbCrLf & "  </td>"
        SourceHTML &= vbCrLf & "  <td width = 124 style='width:93.0pt;border-top:solid black 1.0pt;border-left:"
        SourceHTML &= vbCrLf & "  none;border-bottom:solid black 1.0pt;border-right:none;background:black;"
        SourceHTML &= vbCrLf & "  padding:0in 5.4pt 0in 5.4pt;height:31.9pt'>"
        SourceHTML &= vbCrLf & "  <p Class=MsoNormal align=center style='margin-bottom:0in;margin-bottom:.0001pt;"
        SourceHTML &= vbCrLf & "  text-align:center;line-height:normal'><b><span style='font-family:""Arial"",sans-serif;"
        SourceHTML &= vbCrLf & "  color:white'>Nama Petugas</span></b></p>"
        SourceHTML &= vbCrLf & "  </td>"
        SourceHTML &= vbCrLf & "  <td width = 102 style='width:76.5pt;border-top:solid black 1.0pt;border-left:"
        SourceHTML &= vbCrLf & "  none;border-bottom:solid black 1.0pt;border-right:none;background:black;"
        SourceHTML &= vbCrLf & "  padding:0in 5.4pt 0in 5.4pt;height:31.9pt'>"
        SourceHTML &= vbCrLf & "  <p Class=MsoNormal align=center style='margin-bottom:0in;margin-bottom:.0001pt;"
        SourceHTML &= vbCrLf & "  text-align:center;line-height:normal'><b><span style='font-family:""Arial"",sans-serif;"
        SourceHTML &= vbCrLf & "  color:white'>NISN</span></b></p>"
        SourceHTML &= vbCrLf & "  </td>"
        SourceHTML &= vbCrLf & "  <td width = 126 style='width:94.5pt;border-top:solid black 1.0pt;border-left:"
        SourceHTML &= vbCrLf & "  none;border-bottom:solid black 1.0pt;border-right:none;background:black;"
        SourceHTML &= vbCrLf & "  padding:0in 5.4pt 0in 5.4pt;height:31.9pt'>"
        SourceHTML &= vbCrLf & "  <p Class=MsoNormal align=center style='margin-bottom:0in;margin-bottom:.0001pt;"
        SourceHTML &= vbCrLf & "  text-align:center;line-height:normal'><b><span style='font-family:""Arial"",sans-serif;"
        SourceHTML &= vbCrLf & "  color:white'>Nama Siswa</span></b></p>"
        SourceHTML &= vbCrLf & "  </td>"
        SourceHTML &= vbCrLf & "  <td width = 82 style='width:61.4pt;border-top:solid black 1.0pt;border-left:"
        SourceHTML &= vbCrLf & "  none;border-bottom:solid black 1.0pt;border-right:none;background:black;"
        SourceHTML &= vbCrLf & "  padding:0in 5.4pt 0in 5.4pt;height:31.9pt'>"
        SourceHTML &= vbCrLf & "  <p Class=MsoNormal align=center style='margin-bottom:0in;margin-bottom:.0001pt;"
        SourceHTML &= vbCrLf & "  text-align:center;line-height:normal'><b><span style='font-family:""Arial"",sans-serif;"
        SourceHTML &= vbCrLf & "  color:white'>Kelas</span></b></p>"
        SourceHTML &= vbCrLf & "  </td>"
        SourceHTML &= vbCrLf & "  <td width = 82 style='width:61.5pt;border-top:solid black 1.0pt;border-left:"
        SourceHTML &= vbCrLf & "  none;border-bottom:solid black 1.0pt;border-right:none;background:black;"
        SourceHTML &= vbCrLf & "  padding:0in 5.4pt 0in 5.4pt;height:31.9pt'>"
        SourceHTML &= vbCrLf & "  <p Class=MsoNormal align=center style='margin-bottom:0in;margin-bottom:.0001pt;"
        SourceHTML &= vbCrLf & "  text-align:center;line-height:normal'><b><span style='font-family:""Arial"",sans-serif;"
        SourceHTML &= vbCrLf & "  color:white'>Bulan</span></b></p>"
        SourceHTML &= vbCrLf & "  </td>"
        SourceHTML &= vbCrLf & "  <td width = 64 style='width:48.1pt;border-top:solid black 1.0pt;border-left:"
        SourceHTML &= vbCrLf & "  none;border-bottom:solid black 1.0pt;border-right:none;background:black;"
        SourceHTML &= vbCrLf & "  padding:0in 5.4pt 0in 5.4pt;height:31.9pt'>"
        SourceHTML &= vbCrLf & "  <p Class=MsoNormal align=center style='margin-bottom:0in;margin-bottom:.0001pt;"
        SourceHTML &= vbCrLf & "  text-align:center;line-height:normal'><b><span style='font-family:""Arial"",sans-serif;"
        SourceHTML &= vbCrLf & "  color:white'>Tahun</span></b></p>"
        SourceHTML &= vbCrLf & "  </td>"
        SourceHTML &= vbCrLf & "  <td width = 54 style='width:40.3pt;border-top:solid black 1.0pt;border-left:"
        SourceHTML &= vbCrLf & "  none;border-bottom:solid black 1.0pt;border-right:none;background:black;"
        SourceHTML &= vbCrLf & "  padding:0in 5.4pt 0in 5.4pt;height:31.9pt'>"
        SourceHTML &= vbCrLf & "  <p Class=MsoNormal align=center style='margin-bottom:0in;margin-bottom:.0001pt;"
        SourceHTML &= vbCrLf & "  text-align:center;line-height:normal'><b><span style='font-family:""Arial"",sans-serif;"
        SourceHTML &= vbCrLf & "  color:white'>ID SPP</span></b></p>"
        SourceHTML &= vbCrLf & "  </td>"
        SourceHTML &= vbCrLf & "  <td width = 120 style='width:90.2pt;border:solid black 1.0pt;border-left:none;"
        SourceHTML &= vbCrLf & "  background:black;padding:0in 5.4pt 0in 5.4pt;height:31.9pt'>"
        SourceHTML &= vbCrLf & "  <p Class=MsoNormal align=center style='margin-bottom:0in;margin-bottom:.0001pt;"
        SourceHTML &= vbCrLf & "  text-align:center;line-height:normal'><b><span style='font-family:""Arial"",sans-serif;"
        SourceHTML &= vbCrLf & "  color:white'>Jumlah Bayar</span></b></p>"
        SourceHTML &= vbCrLf & "  </td>"
        SourceHTML &= vbCrLf & " </tr>"
        Dim urutan As Integer = 1
        For Each Isi In Tampung.Select()
            SourceHTML &= vbCrLf & " <tr style ='height:44.5pt'>"
            SourceHTML &= vbCrLf & "  <td width=36 style='width:27.0pt;border:solid #666666 1.0pt;border-top:none;"
            SourceHTML &= vbCrLf & "  background:#CCCCCC;padding:0in 5.4pt 0in 5.4pt;height:44.5pt'>"
            SourceHTML &= vbCrLf & "	  <p class=MsoNormal align=center style='margin-bottom:0in;margin-bottom:.0001pt;"
            SourceHTML &= vbCrLf & "  text-align:center;line-height:normal'><span style='font-family:""Arial"",sans-serif;"
            SourceHTML &= vbCrLf & "  color:black'>" & urutan & "</span></p>"
            SourceHTML &= vbCrLf & "  </td>"
            SourceHTML &= vbCrLf & "  <td width = 99 style='width:74.1pt;border-top:none;border-left:none;border-bottom:"
            SourceHTML &= vbCrLf & "  solid #666666 1.0pt;border-right:solid #666666 1.0pt;background:#CCCCCC;"
            SourceHTML &= vbCrLf & "  padding:0in 5.4pt 0in 5.4pt;height:44.5pt'>"
            SourceHTML &= vbCrLf & "  <p Class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt;line-height:"
            SourceHTML &= vbCrLf & "  normal'><span style='font-family:""Arial"",sans-serif;color:black'>" & Isi.Item("tgl_bayar") & "</span></p>"
            SourceHTML &= vbCrLf & "  </td>"
            SourceHTML &= vbCrLf & "  <td width = 104 style='width:78.15pt;border-top:none;border-left:none;"
            SourceHTML &= vbCrLf & "  border-bottom:solid #666666 1.0pt;border-right:solid #666666 1.0pt;"
            SourceHTML &= vbCrLf & "  background:#CCCCCC;padding:0in 5.4pt 0in 5.4pt;height:44.5pt'>"
            SourceHTML &= vbCrLf & "  <p Class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt;line-height:"
            SourceHTML &= vbCrLf & "  normal'><span style='font-family:""Arial"",sans-serif;color:black'>" & Isi.Item("id_pembayaran") & "</span></p>"
            SourceHTML &= vbCrLf & "  </td>"
            SourceHTML &= vbCrLf & "  <td width = 87 style='width:65.25pt;border-top:none;border-left:none;"
            SourceHTML &= vbCrLf & "  border-bottom:solid #666666 1.0pt;border-right:solid #666666 1.0pt;"
            SourceHTML &= vbCrLf & "  background:#CCCCCC;padding:0in 5.4pt 0in 5.4pt;height:44.5pt'>"
            SourceHTML &= vbCrLf & "  <p Class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt;line-height:"
            SourceHTML &= vbCrLf & "  normal'><span style='font-family:""Arial"",sans-serif;color:black'>" & Isi.Item("id_petugas") & "</span></p>"
            SourceHTML &= vbCrLf & "  </td>"
            SourceHTML &= vbCrLf & "  <td width = 124 style='width:93.0pt;border-top:none;border-left:none;"
            SourceHTML &= vbCrLf & "  border-bottom:solid #666666 1.0pt;border-right:solid #666666 1.0pt;"
            SourceHTML &= vbCrLf & "  background:#CCCCCC;padding:0in 5.4pt 0in 5.4pt;height:44.5pt'>"
            SourceHTML &= vbCrLf & "  <p Class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt;line-height:"
            SourceHTML &= vbCrLf & "  normal'><span style='font-family:""Arial"",sans-serif;color:black'>" & Isi.Item("nama_petugas") & "</span></p>"
            SourceHTML &= vbCrLf & "  </td>"
            SourceHTML &= vbCrLf & "  <td width = 102 style='width:76.5pt;border-top:none;border-left:none;"
            SourceHTML &= vbCrLf & "  border-bottom:solid #666666 1.0pt;border-right:solid #666666 1.0pt;"
            SourceHTML &= vbCrLf & "  background:#CCCCCC;padding:0in 5.4pt 0in 5.4pt;height:44.5pt'>"
            SourceHTML &= vbCrLf & "  <p Class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt;line-height:"
            SourceHTML &= vbCrLf & "  normal'><span style='font-family:""Arial"",sans-serif;color:black'>" & Isi.Item("nisn") & "</span></p>"
            SourceHTML &= vbCrLf & "  </td>"
            SourceHTML &= vbCrLf & "  <td width = 126 style='width:94.5pt;border-top:none;border-left:none;"
            SourceHTML &= vbCrLf & "  border-bottom:solid #666666 1.0pt;border-right:solid #666666 1.0pt;"
            SourceHTML &= vbCrLf & "  background:#CCCCCC;padding:0in 5.4pt 0in 5.4pt;height:44.5pt'>"
            SourceHTML &= vbCrLf & "  <p Class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt;line-height:"
            SourceHTML &= vbCrLf & "  normal'><span style='font-family:""Arial"",sans-serif;color:black'>" & Isi.Item("nama") & "</span></p>"
            SourceHTML &= vbCrLf & "  </td>"
            SourceHTML &= vbCrLf & "  <td width = 82 style='width:61.4pt;border-top:none;border-left:none;border-bottom:"
            SourceHTML &= vbCrLf & "  solid #666666 1.0pt;border-right:solid #666666 1.0pt;background:#CCCCCC;"
            SourceHTML &= vbCrLf & "  padding:0in 5.4pt 0in 5.4pt;height:44.5pt'>"
            SourceHTML &= vbCrLf & "  <p Class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt;line-height:"
            SourceHTML &= vbCrLf & "  normal'><span style='font-family:""Arial"",sans-serif;color:black'>" & Isi.Item("nama_kelas") & "</span></p>"
            SourceHTML &= vbCrLf & "  </td>"
            SourceHTML &= vbCrLf & "  <td width = 82 style='width:61.5pt;border-top:none;border-left:none;border-bottom:"
            SourceHTML &= vbCrLf & "  solid #666666 1.0pt;border-right:solid #666666 1.0pt;background:#CCCCCC;"
            SourceHTML &= vbCrLf & "  padding:0in 5.4pt 0in 5.4pt;height:44.5pt'>"
            SourceHTML &= vbCrLf & "  <p Class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt;line-height:"
            SourceHTML &= vbCrLf & "  normal'><span style='font-family:""Arial"",sans-serif;color:black'>" & Isi.Item("bulan_dibayar") & "</span></p>"
            SourceHTML &= vbCrLf & "  </td>"
            SourceHTML &= vbCrLf & "  <td width = 64 style='width:48.1pt;border-top:none;border-left:none;border-bottom:"
            SourceHTML &= vbCrLf & "  solid #666666 1.0pt;border-right:solid #666666 1.0pt;background:#CCCCCC;"
            SourceHTML &= vbCrLf & "  padding:0in 5.4pt 0in 5.4pt;height:44.5pt'>"
            SourceHTML &= vbCrLf & "  <p Class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt;line-height:"
            SourceHTML &= vbCrLf & "  normal'><span style='font-family:""Arial"",sans-serif;color:black'>" & Isi.Item("tahun_dibayar") & "</span></p>"
            SourceHTML &= vbCrLf & "  </td>"
            SourceHTML &= vbCrLf & "  <td width = 54 style='width:40.3pt;border-top:none;border-left:none;border-bottom:"
            SourceHTML &= vbCrLf & "  solid #666666 1.0pt;border-right:solid #666666 1.0pt;background:#CCCCCC;"
            SourceHTML &= vbCrLf & "  padding:0in 5.4pt 0in 5.4pt;height:44.5pt'>"
            SourceHTML &= vbCrLf & "  <p Class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt;line-height:"
            SourceHTML &= vbCrLf & "  normal'><span style='font-family:""Arial"",sans-serif;color:black'>" & Isi.Item("id_spp") & "</span></p>"
            SourceHTML &= vbCrLf & "  </td>"
            SourceHTML &= vbCrLf & "  <td width = 120 style='width:90.2pt;border-top:none;border-left:none;"
            SourceHTML &= vbCrLf & "  border-bottom:solid #666666 1.0pt;border-right:solid #666666 1.0pt;"
            SourceHTML &= vbCrLf & "  background:#CCCCCC;padding:0in 5.4pt 0in 5.4pt;height:44.5pt'>"
            SourceHTML &= vbCrLf & "  <p Class=MsoNormal align=right style='margin-bottom:0in;margin-bottom:.0001pt;"
            SourceHTML &= vbCrLf & "  text-align:right;line-height:normal'><span style='font-family:""Arial"",sans-serif;"
            SourceHTML &= vbCrLf & "  color:black'>" & Format(Isi.Item("jumlah_bayar"), "Rp ###,###") & "</span></p>"
            SourceHTML &= vbCrLf & "  </td>"
            SourceHTML &= vbCrLf & " </tr>"
            urutan += 1
        Next
        SourceHTML &= vbCrLf & "</table>"

        SourceHTML &= vbCrLf & "<p Class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt'><b><span"
        SourceHTML &= vbCrLf & "style='font-family:""Arial"",sans-serif'>&nbsp;</span></b></p>"

        SourceHTML &= vbCrLf & "<p Class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt'><span"
        SourceHTML &= vbCrLf & "style='font-family:""Arial"",sans-serif'>" & My.Settings.TempatTTD & ", " & Format(Now(), "dd MMMM yyyy") & "</span></p>"

        SourceHTML &= vbCrLf & "<p Class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt'><span"
        SourceHTML &= vbCrLf & "style='font-family:""Arial"",sans-serif'>Mengesahkan,</span></p>"

        SourceHTML &= vbCrLf & "<p Class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt'><span"
        SourceHTML &= vbCrLf & "style='font-family:""Arial"",sans-serif'>&nbsp;</span></p>"

        SourceHTML &= vbCrLf & "<p Class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt'><span"
        SourceHTML &= vbCrLf & "style='font-family:""Arial"",sans-serif'>&nbsp;</span></p>"

        SourceHTML &= vbCrLf & "<p Class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt'><span"
        SourceHTML &= vbCrLf & "style='font-family:""Arial"",sans-serif'>&nbsp;</span></p>"

        SourceHTML &= vbCrLf & "<p Class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt'><span"
        SourceHTML &= vbCrLf & "style='font-family:""Arial"",sans-serif'>&nbsp;</span></p>"

        SourceHTML &= vbCrLf & "<p Class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt'><span"
        SourceHTML &= vbCrLf & "style='font-family:""Arial"",sans-serif'>(................................)</span></p>"

        SourceHTML &= vbCrLf & "<p Class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt'><span"
        SourceHTML &= vbCrLf & "style='font-family:""Arial"",sans-serif'>" & My.Settings.NamaPemimpin & "</span></p>"

        SourceHTML &= vbCrLf & "</div>"

        SourceHTML &= vbCrLf & "</body>"

        SourceHTML &= vbCrLf & "</html>"

        CetakLaporan.SourceHTML = SourceHTML
        CetakLaporan.ShowDialog()
    End Sub
    Sub CetakRekapitulasiPembayaran(ByVal Tampung As DataTable, ByVal Tahun As String)
        Dim SourceHTML As String = ""
        SourceHTML &= vbCrLf & "<html>"
        SourceHTML &= vbCrLf & "<head>"
        SourceHTML &= vbCrLf & "'<meta http-equiv=Content-Type content=""text/html; charset=windows-1252"">"
        SourceHTML &= vbCrLf & "<meta name = Generator content=""Microsoft Word 15 (filtered)"">"
        SourceHTML &= vbCrLf & "<style>"
        SourceHTML &= vbCrLf & "<!--"
        SourceHTML &= vbCrLf & " /* Font Definitions */"
        SourceHTML &= vbCrLf & " @font-face"
        SourceHTML &= vbCrLf & "	{font-family:""Cambria Math"";"
        SourceHTML &= vbCrLf & "	panose-1: 2 4 5 3 5 4 6 3 2 4;}"
        SourceHTML &= vbCrLf & "@font-face"
        SourceHTML &= vbCrLf & "	{font-family:Calibri;"
        SourceHTML &= vbCrLf & "	panose-1: 2 15 5 2 2 2 4 3 2 4;}"
        SourceHTML &= vbCrLf & " /* Style Definitions */"
        SourceHTML &= vbCrLf & " p.MsoNormal, li.MsoNormal, div.MsoNormal"
        SourceHTML &= vbCrLf & "	{margin-top:0in;"
        SourceHTML &= vbCrLf & "	margin-Right(): 0in;"
        SourceHTML &= vbCrLf & "	margin-bottom: 8.0pt;"
        SourceHTML &= vbCrLf & "	margin-Left(): 0in;"
        SourceHTML &= vbCrLf & "	line-height: 107%;"
        SourceHTML &= vbCrLf & "	Font-Size: 11.0pt;"
        SourceHTML &= vbCrLf & "	Font-family: ""Calibri"",sans-serif;}"
        SourceHTML &= vbCrLf & ".MsoChpDefault"
        SourceHTML &= vbCrLf & "	{font-family:""Calibri"",sans-serif;}"
        SourceHTML &= vbCrLf & ".MsoPapDefault"
        SourceHTML &= vbCrLf & "	{margin-bottom:8.0pt;"
        SourceHTML &= vbCrLf & "	line-height: 107%;}"
        SourceHTML &= vbCrLf & "@page WordSection1"
        SourceHTML &= vbCrLf & "	{size:841.9pt 595.3pt;"
        SourceHTML &= vbCrLf & "	margin:.5in .5in .5in .5in;}"
        SourceHTML &= vbCrLf & "div.WordSection1"
        SourceHTML &= vbCrLf & "	{page:WordSection1;}"
        SourceHTML &= vbCrLf & "-->"
        SourceHTML &= vbCrLf & "</style>"

        SourceHTML &= vbCrLf & "</head>"

        SourceHTML &= vbCrLf & "<body lang = EN - US >"

        SourceHTML &= vbCrLf & "<div Class=WordSection1>"

        SourceHTML &= vbCrLf & "<p Class=MsoNormal align=center style='margin-bottom:0in;margin-bottom:.0001pt;"
        SourceHTML &= vbCrLf & "text-align:center'><b><span style='font-size:14.0pt;line-height:107%;"
        SourceHTML &= vbCrLf & "font-family:""Arial"",sans-serif'>LAPORAN REKAPITULASI PEMBAYARAN</span></b></p>"

        SourceHTML &= vbCrLf & "<p Class=MsoNormal align=center style='margin-bottom:0in;margin-bottom:.0001pt;"
        SourceHTML &= vbCrLf & "text-align:center'><b><span style='font-size:14.0pt;line-height:107%;"
        SourceHTML &= vbCrLf & "font-family:""Arial"",sans-serif'>PERIODE TAHUN " & Tahun & "  </span></b></p>"

        SourceHTML &= vbCrLf & "<p Class=MsoNormal align=center style='margin-bottom:0in;margin-bottom:.0001pt;"
        SourceHTML &= vbCrLf & "text-align:center'><b><span style='font-family:""Arial"",sans-serif'>&nbsp;</span></b></p>"

        SourceHTML &= vbCrLf & "<table>"
        SourceHTML &= vbCrLf & "<tr>"
        SourceHTML &= vbCrLf & "<td>Id Admin </td>"
        SourceHTML &= vbCrLf & "<td>: " & My.Settings.CurrentId & " </td>"
        SourceHTML &= vbCrLf & "</tr>"
        SourceHTML &= vbCrLf & "<tr>"
        SourceHTML &= vbCrLf & "<td>Nama Admin </td>"
        SourceHTML &= vbCrLf & "<td>: " & My.Settings.Username & " </td>"
        SourceHTML &= vbCrLf & "</tr>"
        SourceHTML &= vbCrLf & "</table>"

        SourceHTML &= vbCrLf & "<table Class=MsoTable15Grid4 border=1 cellspacing=0 cellpadding=0 width=1080"
        SourceHTML &= vbCrLf & " style='width:11.25in;margin-left:-18.25pt;border-collapse:collapse;border:"
        SourceHTML &= vbCrLf & " none;margin:0 auto'>"
        SourceHTML &= vbCrLf & " <tr style ='height:31.9pt'>"

        SourceHTML &= vbCrLf & "  <td width=36 style='width:27.0pt;border:solid black 1.0pt;border-right:none;"
        SourceHTML &= vbCrLf & "  background:black;padding:0in 5.4pt 0in 5.4pt;height:31.9pt'>"
        SourceHTML &= vbCrLf & "	  <p class=MsoNormal align=center style='margin-bottom:0in;margin-bottom:.0001pt;"
        SourceHTML &= vbCrLf & "  text-align:center;line-height:normal'><b><span style='font-family:""Arial"",sans-serif;"
        SourceHTML &= vbCrLf & "  color:white'>No</span></b></p>"
        SourceHTML &= vbCrLf & "  </td>"

        SourceHTML &= vbCrLf & "  <td width = 99 style='width:74.1pt;border-top:solid black 1.0pt;border-left:"
        SourceHTML &= vbCrLf & "  none;border-bottom:solid black 1.0pt;border-right:none;background:black;"
        SourceHTML &= vbCrLf & "  padding:0in 5.4pt 0in 5.4pt;height:31.9pt'>"
        SourceHTML &= vbCrLf & "  <p Class=MsoNormal align=center style='margin-bottom:0in;margin-bottom:.0001pt;"
        SourceHTML &= vbCrLf & "  text-align:center;line-height:normal'><b><span style='font-family:""Arial"",sans-serif;"
        SourceHTML &= vbCrLf & "  color:white'>Nama Siswa</span></b></p>"
        SourceHTML &= vbCrLf & "  </td>"

        SourceHTML &= vbCrLf & "  <td width = 104 style='width:78.15pt;border-top:solid black 1.0pt;border-left:"
        SourceHTML &= vbCrLf & "  none;border-bottom:solid black 1.0pt;border-right:none;background:black;"
        SourceHTML &= vbCrLf & "  padding:0in 5.4pt 0in 5.4pt;height:31.9pt'>"
        SourceHTML &= vbCrLf & "  <p Class=MsoNormal align=center style='margin-bottom:0in;margin-bottom:.0001pt;"
        SourceHTML &= vbCrLf & "  text-align:center;line-height:normal'><b><span style='font-family:""Arial"",sans-serif;"
        SourceHTML &= vbCrLf & "  color:white'>Nama</span></b></p>"
        SourceHTML &= vbCrLf & "  <p Class=MsoNormal align=center style='margin-bottom:0in;margin-bottom:.0001pt;"
        SourceHTML &= vbCrLf & "  text-align:center;line-height:normal'><b><span style='font-family:""Arial"",sans-serif;"
        SourceHTML &= vbCrLf & "  color:white'> Kelas</span></b></p>"
        SourceHTML &= vbCrLf & "  </td>"

        SourceHTML &= vbCrLf & "  <td width = 87 style='width:65.25pt;border-top:solid black 1.0pt;border-left:"
        SourceHTML &= vbCrLf & "  none;border-bottom:solid black 1.0pt;border-right:none;background:black;"
        SourceHTML &= vbCrLf & "  padding:0in 5.4pt 0in 5.4pt;height:31.9pt'>"
        SourceHTML &= vbCrLf & "  <p Class=MsoNormal align=center style='margin-bottom:0in;margin-bottom:.0001pt;"
        SourceHTML &= vbCrLf & "  text-align:center;line-height:normal'><b><span style='font-family:""Arial"",sans-serif;"
        SourceHTML &= vbCrLf & "  color:white'>Januari</span></b></p>"
        SourceHTML &= vbCrLf & "  </td>"

        SourceHTML &= vbCrLf & "  <td width = 124 style='width:93.0pt;border-top:solid black 1.0pt;border-left:"
        SourceHTML &= vbCrLf & "  none;border-bottom:solid black 1.0pt;border-right:none;background:black;"
        SourceHTML &= vbCrLf & "  padding:0in 5.4pt 0in 5.4pt;height:31.9pt'>"
        SourceHTML &= vbCrLf & "  <p Class=MsoNormal align=center style='margin-bottom:0in;margin-bottom:.0001pt;"
        SourceHTML &= vbCrLf & "  text-align:center;line-height:normal'><b><span style='font-family:""Arial"",sans-serif;"
        SourceHTML &= vbCrLf & "  color:white'>Februari</span></b></p>"
        SourceHTML &= vbCrLf & "  </td>"

        SourceHTML &= vbCrLf & "  <td width = 102 style='width:76.5pt;border-top:solid black 1.0pt;border-left:"
        SourceHTML &= vbCrLf & "  none;border-bottom:solid black 1.0pt;border-right:none;background:black;"
        SourceHTML &= vbCrLf & "  padding:0in 5.4pt 0in 5.4pt;height:31.9pt'>"
        SourceHTML &= vbCrLf & "  <p Class=MsoNormal align=center style='margin-bottom:0in;margin-bottom:.0001pt;"
        SourceHTML &= vbCrLf & "  text-align:center;line-height:normal'><b><span style='font-family:""Arial"",sans-serif;"
        SourceHTML &= vbCrLf & "  color:white'>Maret</span></b></p>"
        SourceHTML &= vbCrLf & "  </td>"

        SourceHTML &= vbCrLf & "  <td width = 126 style='width:94.5pt;border-top:solid black 1.0pt;border-left:"
        SourceHTML &= vbCrLf & "  none;border-bottom:solid black 1.0pt;border-right:none;background:black;"
        SourceHTML &= vbCrLf & "  padding:0in 5.4pt 0in 5.4pt;height:31.9pt'>"
        SourceHTML &= vbCrLf & "  <p Class=MsoNormal align=center style='margin-bottom:0in;margin-bottom:.0001pt;"
        SourceHTML &= vbCrLf & "  text-align:center;line-height:normal'><b><span style='font-family:""Arial"",sans-serif;"
        SourceHTML &= vbCrLf & "  color:white'>April</span></b></p>"
        SourceHTML &= vbCrLf & "  </td>"

        SourceHTML &= vbCrLf & "  <td width = 82 style='width:61.4pt;border-top:solid black 1.0pt;border-left:"
        SourceHTML &= vbCrLf & "  none;border-bottom:solid black 1.0pt;border-right:none;background:black;"
        SourceHTML &= vbCrLf & "  padding:0in 5.4pt 0in 5.4pt;height:31.9pt'>"
        SourceHTML &= vbCrLf & "  <p Class=MsoNormal align=center style='margin-bottom:0in;margin-bottom:.0001pt;"
        SourceHTML &= vbCrLf & "  text-align:center;line-height:normal'><b><span style='font-family:""Arial"",sans-serif;"
        SourceHTML &= vbCrLf & "  color:white'>Mei</span></b></p>"
        SourceHTML &= vbCrLf & "  </td>"

        SourceHTML &= vbCrLf & "  <td width = 82 style='width:61.5pt;border-top:solid black 1.0pt;border-left:"
        SourceHTML &= vbCrLf & "  none;border-bottom:solid black 1.0pt;border-right:none;background:black;"
        SourceHTML &= vbCrLf & "  padding:0in 5.4pt 0in 5.4pt;height:31.9pt'>"
        SourceHTML &= vbCrLf & "  <p Class=MsoNormal align=center style='margin-bottom:0in;margin-bottom:.0001pt;"
        SourceHTML &= vbCrLf & "  text-align:center;line-height:normal'><b><span style='font-family:""Arial"",sans-serif;"
        SourceHTML &= vbCrLf & "  color:white'>Juni</span></b></p>"
        SourceHTML &= vbCrLf & "  </td>"

        SourceHTML &= vbCrLf & "  <td width = 64 style='width:48.1pt;border-top:solid black 1.0pt;border-left:"
        SourceHTML &= vbCrLf & "  none;border-bottom:solid black 1.0pt;border-right:none;background:black;"
        SourceHTML &= vbCrLf & "  padding:0in 5.4pt 0in 5.4pt;height:31.9pt'>"
        SourceHTML &= vbCrLf & "  <p Class=MsoNormal align=center style='margin-bottom:0in;margin-bottom:.0001pt;"
        SourceHTML &= vbCrLf & "  text-align:center;line-height:normal'><b><span style='font-family:""Arial"",sans-serif;"
        SourceHTML &= vbCrLf & "  color:white'>Juli</span></b></p>"
        SourceHTML &= vbCrLf & "  </td>"

        SourceHTML &= vbCrLf & "  <td width = 54 style='width:40.3pt;border-top:solid black 1.0pt;border-left:"
        SourceHTML &= vbCrLf & "  none;border-bottom:solid black 1.0pt;border-right:none;background:black;"
        SourceHTML &= vbCrLf & "  padding:0in 5.4pt 0in 5.4pt;height:31.9pt'>"
        SourceHTML &= vbCrLf & "  <p Class=MsoNormal align=center style='margin-bottom:0in;margin-bottom:.0001pt;"
        SourceHTML &= vbCrLf & "  text-align:center;line-height:normal'><b><span style='font-family:""Arial"",sans-serif;"
        SourceHTML &= vbCrLf & "  color:white'>Agustus</span></b></p>"
        SourceHTML &= vbCrLf & "  </td>"

        SourceHTML &= vbCrLf & "  <td width = 120 style='width:90.2pt;border:solid black 1.0pt;border-left:none;"
        SourceHTML &= vbCrLf & "  background:black;padding:0in 5.4pt 0in 5.4pt;height:31.9pt'>"
        SourceHTML &= vbCrLf & "  <p Class=MsoNormal align=center style='margin-bottom:0in;margin-bottom:.0001pt;"
        SourceHTML &= vbCrLf & "  text-align:center;line-height:normal'><b><span style='font-family:""Arial"",sans-serif;"
        SourceHTML &= vbCrLf & "  color:white'>September</span></b></p>"
        SourceHTML &= vbCrLf & "  </td>"

        SourceHTML &= vbCrLf & "  <td width = 120 style='width:90.2pt;border:solid black 1.0pt;border-left:none;"
        SourceHTML &= vbCrLf & "  background:black;padding:0in 5.4pt 0in 5.4pt;height:31.9pt'>"
        SourceHTML &= vbCrLf & "  <p Class=MsoNormal align=center style='margin-bottom:0in;margin-bottom:.0001pt;"
        SourceHTML &= vbCrLf & "  text-align:center;line-height:normal'><b><span style='font-family:""Arial"",sans-serif;"
        SourceHTML &= vbCrLf & "  color:white'>Oktober</span></b></p>"
        SourceHTML &= vbCrLf & "  </td>"

        SourceHTML &= vbCrLf & "  <td width = 120 style='width:90.2pt;border:solid black 1.0pt;border-left:none;"
        SourceHTML &= vbCrLf & "  background:black;padding:0in 5.4pt 0in 5.4pt;height:31.9pt'>"
        SourceHTML &= vbCrLf & "  <p Class=MsoNormal align=center style='margin-bottom:0in;margin-bottom:.0001pt;"
        SourceHTML &= vbCrLf & "  text-align:center;line-height:normal'><b><span style='font-family:""Arial"",sans-serif;"
        SourceHTML &= vbCrLf & "  color:white'>November</span></b></p>"
        SourceHTML &= vbCrLf & "  </td>"

        SourceHTML &= vbCrLf & "  <td width = 120 style='width:90.2pt;border:solid black 1.0pt;border-left:none;"
        SourceHTML &= vbCrLf & "  background:black;padding:0in 5.4pt 0in 5.4pt;height:31.9pt'>"
        SourceHTML &= vbCrLf & "  <p Class=MsoNormal align=center style='margin-bottom:0in;margin-bottom:.0001pt;"
        SourceHTML &= vbCrLf & "  text-align:center;line-height:normal'><b><span style='font-family:""Arial"",sans-serif;"
        SourceHTML &= vbCrLf & "  color:white'>Desember</span></b></p>"
        SourceHTML &= vbCrLf & "  </td>"

        SourceHTML &= vbCrLf & "  <td width = 120 style='width:90.2pt;border:solid black 1.0pt;border-left:none;"
        SourceHTML &= vbCrLf & "  background:black;padding:0in 5.4pt 0in 5.4pt;height:31.9pt'>"
        SourceHTML &= vbCrLf & "  <p Class=MsoNormal align=center style='margin-bottom:0in;margin-bottom:.0001pt;"
        SourceHTML &= vbCrLf & "  text-align:center;line-height:normal'><b><span style='font-family:""Arial"",sans-serif;"
        SourceHTML &= vbCrLf & "  color:white'>Total Pembayaran</span></b></p>"
        SourceHTML &= vbCrLf & "  </td>"

        SourceHTML &= vbCrLf & " </tr>"
        Dim urutan As Integer = 1
        For Each Isi In Tampung.Select()
            SourceHTML &= vbCrLf & " <tr style ='height:44.5pt'>"

            SourceHTML &= vbCrLf & "  <td width=36 style='width:27.0pt;border:solid #666666 1.0pt;border-top:none;"
            SourceHTML &= vbCrLf & "  background:#CCCCCC;padding:0in 5.4pt 0in 5.4pt;height:44.5pt'>"
            SourceHTML &= vbCrLf & "	  <p class=MsoNormal align=center style='margin-bottom:0in;margin-bottom:.0001pt;"
            SourceHTML &= vbCrLf & "  text-align:center;line-height:normal'><span style='font-family:""Arial"",sans-serif;"
            SourceHTML &= vbCrLf & "  color:black'>" & urutan & "</span></p>"
            SourceHTML &= vbCrLf & "  </td>"

            SourceHTML &= vbCrLf & "  <td width = 99 style='width:74.1pt;border-top:none;border-left:none;border-bottom:"
            SourceHTML &= vbCrLf & "  solid #666666 1.0pt;border-right:solid #666666 1.0pt;background:#CCCCCC;"
            SourceHTML &= vbCrLf & "  padding:0in 5.4pt 0in 5.4pt;height:44.5pt'>"
            SourceHTML &= vbCrLf & "  <p Class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt;line-height:"
            SourceHTML &= vbCrLf & "  normal'><span style='font-family:""Arial"",sans-serif;color:black'>" & Isi.Item("Nama_Siswa") & "</span></p>"
            SourceHTML &= vbCrLf & "  </td>"

            SourceHTML &= vbCrLf & "  <td width = 104 style='width:78.15pt;border-top:none;border-left:none;"
            SourceHTML &= vbCrLf & "  border-bottom:solid #666666 1.0pt;border-right:solid #666666 1.0pt;"
            SourceHTML &= vbCrLf & "  background:#CCCCCC;padding:0in 5.4pt 0in 5.4pt;height:44.5pt'>"
            SourceHTML &= vbCrLf & "  <p Class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt;line-height:"
            SourceHTML &= vbCrLf & "  normal'><span style='font-family:""Arial"",sans-serif;color:black'>" & Isi.Item("Kelas") & "</span></p>"
            SourceHTML &= vbCrLf & "  </td>"

            SourceHTML &= vbCrLf & "  <td width = 87 style='width:65.25pt;border-top:none;border-left:none;"
            SourceHTML &= vbCrLf & "  border-bottom:solid #666666 1.0pt;border-right:solid #666666 1.0pt;"
            SourceHTML &= vbCrLf & "  background:#CCCCCC;padding:0in 5.4pt 0in 5.4pt;height:44.5pt'>"
            SourceHTML &= vbCrLf & "  <p Class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt;line-height:"
            SourceHTML &= vbCrLf & "  normal;text-align:right;'><span style='font-family:""Arial"",sans-serif;color:black'>" & Isi.Item("Januari_" & Tahun) & "</span></p>"
            SourceHTML &= vbCrLf & "  </td>"

            SourceHTML &= vbCrLf & "  <td width = 124 style='width:93.0pt;border-top:none;border-left:none;"
            SourceHTML &= vbCrLf & "  border-bottom:solid #666666 1.0pt;border-right:solid #666666 1.0pt;"
            SourceHTML &= vbCrLf & "  background:#CCCCCC;padding:0in 5.4pt 0in 5.4pt;height:44.5pt'>"
            SourceHTML &= vbCrLf & "  <p Class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt;line-height:"
            SourceHTML &= vbCrLf & "  normal;text-align:right;'><span style='font-family:""Arial"",sans-serif;color:black'>" & Isi.Item("Februari_" & Tahun) & "</span></p>"
            SourceHTML &= vbCrLf & "  </td>"

            SourceHTML &= vbCrLf & "  <td width = 102 style='width:76.5pt;border-top:none;border-left:none;"
            SourceHTML &= vbCrLf & "  border-bottom:solid #666666 1.0pt;border-right:solid #666666 1.0pt;"
            SourceHTML &= vbCrLf & "  background:#CCCCCC;padding:0in 5.4pt 0in 5.4pt;height:44.5pt'>"
            SourceHTML &= vbCrLf & "  <p Class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt;line-height:"
            SourceHTML &= vbCrLf & "  normal;text-align:right;'><span style='font-family:""Arial"",sans-serif;color:black'>" & Isi.Item("Maret_" & Tahun) & "</span></p>"
            SourceHTML &= vbCrLf & "  </td>"

            SourceHTML &= vbCrLf & "  <td width = 126 style='width:94.5pt;border-top:none;border-left:none;"
            SourceHTML &= vbCrLf & "  border-bottom:solid #666666 1.0pt;border-right:solid #666666 1.0pt;"
            SourceHTML &= vbCrLf & "  background:#CCCCCC;padding:0in 5.4pt 0in 5.4pt;height:44.5pt'>"
            SourceHTML &= vbCrLf & "  <p Class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt;line-height:"
            SourceHTML &= vbCrLf & "  normal;text-align:right;'><span style='font-family:""Arial"",sans-serif;color:black'>" & Isi.Item("April_" & Tahun) & "</span></p>"
            SourceHTML &= vbCrLf & "  </td>"

            SourceHTML &= vbCrLf & "  <td width = 82 style='width:61.4pt;border-top:none;border-left:none;border-bottom:"
            SourceHTML &= vbCrLf & "  solid #666666 1.0pt;border-right:solid #666666 1.0pt;background:#CCCCCC;"
            SourceHTML &= vbCrLf & "  padding:0in 5.4pt 0in 5.4pt;height:44.5pt'>"
            SourceHTML &= vbCrLf & "  <p Class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt;line-height:"
            SourceHTML &= vbCrLf & "  normal;text-align:right;'><span style='font-family:""Arial"",sans-serif;color:black'>" & Isi.Item("Mei_" & Tahun) & "</span></p>"
            SourceHTML &= vbCrLf & "  </td>"

            SourceHTML &= vbCrLf & "  <td width = 82 style='width:61.5pt;border-top:none;border-left:none;border-bottom:"
            SourceHTML &= vbCrLf & "  solid #666666 1.0pt;border-right:solid #666666 1.0pt;background:#CCCCCC;"
            SourceHTML &= vbCrLf & "  padding:0in 5.4pt 0in 5.4pt;height:44.5pt'>"
            SourceHTML &= vbCrLf & "  <p Class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt;line-height:"
            SourceHTML &= vbCrLf & "  normal;text-align:right;'><span style='font-family:""Arial"",sans-serif;color:black'>" & Isi.Item("Juni_" & Tahun) & "</span></p>"
            SourceHTML &= vbCrLf & "  </td>"

            SourceHTML &= vbCrLf & "  <td width = 64 style='width:48.1pt;border-top:none;border-left:none;border-bottom:"
            SourceHTML &= vbCrLf & "  solid #666666 1.0pt;border-right:solid #666666 1.0pt;background:#CCCCCC;"
            SourceHTML &= vbCrLf & "  padding:0in 5.4pt 0in 5.4pt;height:44.5pt'>"
            SourceHTML &= vbCrLf & "  <p Class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt;line-height:"
            SourceHTML &= vbCrLf & "  normal;text-align:right;'><span style='font-family:""Arial"",sans-serif;color:black'>" & Isi.Item("Juli_" & Tahun) & "</span></p>"
            SourceHTML &= vbCrLf & "  </td>"

            SourceHTML &= vbCrLf & "  <td width = 54 style='width:40.3pt;border-top:none;border-left:none;border-bottom:"
            SourceHTML &= vbCrLf & "  solid #666666 1.0pt;border-right:solid #666666 1.0pt;background:#CCCCCC;"
            SourceHTML &= vbCrLf & "  padding:0in 5.4pt 0in 5.4pt;height:44.5pt'>"
            SourceHTML &= vbCrLf & "  <p Class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt;line-height:"
            SourceHTML &= vbCrLf & "  normal;text-align:right;'><span style='font-family:""Arial"",sans-serif;color:black'>" & Isi.Item("Agustus_" & Tahun) & "</span></p>"
            SourceHTML &= vbCrLf & "  </td>"

            SourceHTML &= vbCrLf & "  <td width = 120 style='width:90.2pt;border-top:none;border-left:none;"
            SourceHTML &= vbCrLf & "  border-bottom:solid #666666 1.0pt;border-right:solid #666666 1.0pt;"
            SourceHTML &= vbCrLf & "  background:#CCCCCC;padding:0in 5.4pt 0in 5.4pt;height:44.5pt'>"
            SourceHTML &= vbCrLf & "  <p Class=MsoNormal align=right style='margin-bottom:0in;margin-bottom:.0001pt;"
            SourceHTML &= vbCrLf & "  text-align:right;line-height:normal'><span style='font-family:""Arial"",sans-serif;"
            SourceHTML &= vbCrLf & "  color:black'>" & Isi.Item("September_" & Tahun) & "</span></p>"
            SourceHTML &= vbCrLf & "  </td>"

            SourceHTML &= vbCrLf & "  <td width = 120 style='width:90.2pt;border-top:none;border-left:none;"
            SourceHTML &= vbCrLf & "  border-bottom:solid #666666 1.0pt;border-right:solid #666666 1.0pt;"
            SourceHTML &= vbCrLf & "  background:#CCCCCC;padding:0in 5.4pt 0in 5.4pt;height:44.5pt'>"
            SourceHTML &= vbCrLf & "  <p Class=MsoNormal align=right style='margin-bottom:0in;margin-bottom:.0001pt;"
            SourceHTML &= vbCrLf & "  text-align:right;line-height:normal'><span style='font-family:""Arial"",sans-serif;"
            SourceHTML &= vbCrLf & "  color:black'>" & Isi.Item("Oktober_" & Tahun) & "</span></p>"
            SourceHTML &= vbCrLf & "  </td>"

            SourceHTML &= vbCrLf & "  <td width = 120 style='width:90.2pt;border-top:none;border-left:none;"
            SourceHTML &= vbCrLf & "  border-bottom:solid #666666 1.0pt;border-right:solid #666666 1.0pt;"
            SourceHTML &= vbCrLf & "  background:#CCCCCC;padding:0in 5.4pt 0in 5.4pt;height:44.5pt'>"
            SourceHTML &= vbCrLf & "  <p Class=MsoNormal align=right style='margin-bottom:0in;margin-bottom:.0001pt;"
            SourceHTML &= vbCrLf & "  text-align:right;line-height:normal'><span style='font-family:""Arial"",sans-serif;"
            SourceHTML &= vbCrLf & "  color:black'>" & Isi.Item("November_" & Tahun) & "</span></p>"
            SourceHTML &= vbCrLf & "  </td>"

            SourceHTML &= vbCrLf & "  <td width = 120 style='width:90.2pt;border-top:none;border-left:none;"
            SourceHTML &= vbCrLf & "  border-bottom:solid #666666 1.0pt;border-right:solid #666666 1.0pt;"
            SourceHTML &= vbCrLf & "  background:#CCCCCC;padding:0in 5.4pt 0in 5.4pt;height:44.5pt'>"
            SourceHTML &= vbCrLf & "  <p Class=MsoNormal align=right style='margin-bottom:0in;margin-bottom:.0001pt;"
            SourceHTML &= vbCrLf & "  text-align:right;line-height:normal'><span style='font-family:""Arial"",sans-serif;"
            SourceHTML &= vbCrLf & "  color:black'>" & Isi.Item("Desember_" & Tahun) & "</span></p>"
            SourceHTML &= vbCrLf & "  </td>"

            SourceHTML &= vbCrLf & "  <td width = 120 style='width:90.2pt;border-top:none;border-left:none;"
            SourceHTML &= vbCrLf & "  border-bottom:solid #666666 1.0pt;border-right:solid #666666 1.0pt;"
            SourceHTML &= vbCrLf & "  background:#CCCCCC;padding:0in 5.4pt 0in 5.4pt;height:44.5pt'>"
            SourceHTML &= vbCrLf & "  <p Class=MsoNormal align=right style='margin-bottom:0in;margin-bottom:.0001pt;"
            SourceHTML &= vbCrLf & "  text-align:right;line-height:normal'><span style='font-family:""Arial"",sans-serif;"
            SourceHTML &= vbCrLf & "  color:black'>" & Format(Isi.Item("Total_Pembayaran"), "Rp ###,###") & "</span></p>"
            SourceHTML &= vbCrLf & "  </td>"

            SourceHTML &= vbCrLf & " </tr>"
            urutan += 1
        Next
        SourceHTML &= vbCrLf & "</table>"

        SourceHTML &= vbCrLf & "<p Class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt'><b><span"
        SourceHTML &= vbCrLf & "style='font-family:""Arial"",sans-serif'>&nbsp;</span></b></p>"

        SourceHTML &= vbCrLf & "<p Class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt'><span"
        SourceHTML &= vbCrLf & "style='font-family:""Arial"",sans-serif'>" & My.Settings.TempatTTD & ", " & Format(Now(), "dd MMMM yyyy") & "</span></p>"

        SourceHTML &= vbCrLf & "<p Class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt'><span"
        SourceHTML &= vbCrLf & "style='font-family:""Arial"",sans-serif'>Mengesahkan,</span></p>"

        SourceHTML &= vbCrLf & "<p Class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt'><span"
        SourceHTML &= vbCrLf & "style='font-family:""Arial"",sans-serif'>&nbsp;</span></p>"

        SourceHTML &= vbCrLf & "<p Class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt'><span"
        SourceHTML &= vbCrLf & "style='font-family:""Arial"",sans-serif'>&nbsp;</span></p>"

        SourceHTML &= vbCrLf & "<p Class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt'><span"
        SourceHTML &= vbCrLf & "style='font-family:""Arial"",sans-serif'>&nbsp;</span></p>"

        SourceHTML &= vbCrLf & "<p Class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt'><span"
        SourceHTML &= vbCrLf & "style='font-family:""Arial"",sans-serif'>&nbsp;</span></p>"

        SourceHTML &= vbCrLf & "<p Class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt'><span"
        SourceHTML &= vbCrLf & "style='font-family:""Arial"",sans-serif'>(................................)</span></p>"

        SourceHTML &= vbCrLf & "<p Class=MsoNormal style='margin-bottom:0in;margin-bottom:.0001pt'><span"
        SourceHTML &= vbCrLf & "style='font-family:""Arial"",sans-serif'>" & My.Settings.NamaPemimpin & "</span></p>"

        SourceHTML &= vbCrLf & "</div>"

        SourceHTML &= vbCrLf & "</body>"

        SourceHTML &= vbCrLf & "</html>"

        CetakLaporan.SourceHTML = SourceHTML
        CetakLaporan.ShowDialog()
    End Sub

End Module
